'use client';

import { useEffect, useState } from 'react';
import { collection, query, where, orderBy, limit, getDocs } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { Card, CardContent } from '@/components/ui/card';
import { Trophy, TrendingUp, Copy, Check } from 'lucide-react';
import { motion } from 'motion/react';
import { Button } from '@/components/ui/button';

interface PublicTweet {
  id: string;
  content: string;
  viralityScore: number;
  topic: string;
}

export default function Leaderboard() {
  const [tweets, setTweets] = useState<PublicTweet[]>([]);
  const [loading, setLoading] = useState(true);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  useEffect(() => {
    fetchLeaderboard();
  }, []);

  const fetchLeaderboard = async () => {
    try {
      // Fetch tweets that are public, ordered by virality score
      const q = query(
        collection(db, 'tweets'),
        where('isPublic', '==', true),
        orderBy('viralityScore', 'desc'),
        limit(20)
      );
      
      const snapshot = await getDocs(q);
      const publicTweets: PublicTweet[] = [];
      
      snapshot.forEach((doc) => {
        const data = doc.data();
        if (data.type === 'tweet') {
          try {
            const parsedContent = JSON.parse(data.content);
            // Find the highest scoring tweet in this generation
            const bestTweet = parsedContent.reduce((prev: any, current: any) => 
              (prev.score > current.score) ? prev : current
            );
            
            publicTweets.push({
              id: doc.id,
              content: bestTweet.tweet,
              viralityScore: bestTweet.score || data.viralityScore || 0,
              topic: data.topic
            });
          } catch (e) {
            console.error("Error parsing tweet content", e);
          }
        }
      });
      
      // Sort again just in case
      publicTweets.sort((a, b) => b.viralityScore - a.viralityScore);
      setTweets(publicTweets);
    } catch (error) {
      console.error("Error fetching leaderboard:", error);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="mb-12 text-center">
        <div className="w-16 h-16 bg-yellow-500/20 rounded-full flex items-center justify-center mx-auto mb-6">
          <Trophy className="w-8 h-8 text-yellow-500" />
        </div>
        <h1 className="text-4xl md:text-5xl font-display font-bold mb-4">Hall of Fame</h1>
        <p className="text-xl text-white/60 max-w-2xl mx-auto">
          The most viral tweets generated by our community.
        </p>
      </div>

      {loading ? (
        <div className="flex justify-center py-20">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
        </div>
      ) : tweets.length === 0 ? (
        <div className="text-center py-20 text-white/40">
          <p>No public tweets yet. Be the first to share yours!</p>
        </div>
      ) : (
        <div className="space-y-6">
          {tweets.map((tweet, idx) => (
            <motion.div
              key={tweet.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.05 }}
            >
              <Card className="bg-white/5 border-white/10 hover:border-white/20 transition-colors relative overflow-hidden">
                <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-yellow-500 to-primary" />
                <CardContent className="p-6">
                  <div className="flex justify-between items-start mb-4">
                    <div className="flex items-center gap-4">
                      <div className="text-2xl font-display font-bold text-white/20">#{idx + 1}</div>
                      <div className="px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1 bg-yellow-500/20 text-yellow-500">
                        <TrendingUp className="w-3 h-3" />
                        Score: {tweet.viralityScore}
                      </div>
                    </div>
                    <Button 
                      variant="ghost" 
                      size="sm" 
                      onClick={() => copyToClipboard(tweet.content, idx)}
                      className="text-white/60 hover:text-white hover:bg-white/10 h-8"
                    >
                      {copiedIndex === idx ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
                    </Button>
                  </div>
                  <p className="text-white/90 whitespace-pre-wrap leading-relaxed text-lg">{tweet.content}</p>
                  <div className="mt-4 text-xs text-white/40">
                    Topic: {tweet.topic}
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}
